### ISSUE TITLE
Missing Constraint error on installing odl-cup to ODL-karaf SR3 distribution.

### ISSUE THREAD

**Issue by subh007** [sniggel/odl-mdsal-cup-example#3]
I am able build the application successfully and trying to install it to the ODL karaf SR3 distribution but I am getting following error:

`opendaylight-user@root>feature:install odl-cup`

`Error executing command: Could not start bundle mvn:org.opendaylight.sample/cup/0.1.0-SNAPSHOT in feature(s) odl-cup-0.1.0-SNAPSHOT: The bundle "org.opendaylight.sample.cup_0.1.0.SNAPSHOT [257]" could not be resolved. Reason: Missing Constraint: Import-Package: org.opendaylight.yangtools.concepts; version="[0.7.0,1.0.0)"
`

I was getting the similar error for `com.google.common.base` but that gets resolved by deploying the `guava-18.0.jar` to ODL (in deploy folder).

Please suggest me how to resolve this error and also please let me know if I am missing anything or any step here.

**Comment by sniggel** [comment]
Hello Kumar, I am trying to fix the com.google.common.base issue which should be a guava lib by having it in the features file so that fols don't have to drop it into the karaf instance by hand.

As for the error you're getting, I'll try and look into it after I fix the guava error. I currently do not know how to fix it.

**Comment by sniggel** [comment]
Kumar, I reread your comment, with this newer code, you don't need SR3 because there is a distribution included with it. This version of OpenDaylight is closer to the Lithium version.

**Comment by subh007** [comment]
@sniggel thanks for your comments.

I would like to add this feature to SR3 karaf distribution as a hot deployment of feature to any ODL distribution. 

I think, I lack the understanding of sup-project cup-karaf. I am not clear why we would we need cup-karaf subproject for feature deployment. Why it is not recommended to deploy the feature to ODL distribution?

Please explain the above questions.

**Comment by sniggel** [comment]
Hello Kumar, I will try to write a deployment guide to deploy this into SR3 if I have the time. You could take all the jars of the project and put them in your SR3 release while karaf is running, but I find this way messy.

Just to be clear, there is Helium (SR3), then Lithium and then Berylium. The upcoming Lithium RC0 release will happen on 6/25/2015

For your questions:
- The cup-karaf is not a subproject, it is a **distribution** for the cup.
- It is not recommended because of the newer versions in the cup **might** not work with the old versions in the Helium release.

Just to be clear, the cup-karaf is a distribution that is closer to the Berylium.

**Comment by subh007** [comment]
@sniggel please let me know when you finish writing the deployment guide.

Thanks !!

**Comment by subh007** [comment]
Hello @sniggel,

I wrote one sample application (https://github.com/subh007/ODL-Sample-App) by following the ODL wiki, I am able to deploy the code to the SR3 distribution and it is working. But whenever I install the `openflowplugin` feature it throws the import conflict error.

Issue detail: https://ask.opendaylight.org/question/3837/error-on-installing-odl-openflowplugin-all-to-sr3-distribution/

Could you please take a look on it, I am not able to resolve this issue. I would like to include the openflowplugin feature so that I can communicate with OF devices by the application.

Thanks !

**Comment by sniggel** [comment]
Cool. I'm closing this issue.

**Comment by subh007** [comment]
@sniggel could you please help me for resolving the import conflict in my application.

**Comment by sniggel** [comment]
I replied to your question on ask.odl.com

**Comment by subh007** [comment]
@sniggel Thank you so much for you help !!
I will try to follow the answer it and I will let you know.

If you don't mind then can I ask you for your e-mail or any medium to contact you for any query/ help?
